language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"