language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
before_script:
  - npm install -g grunt-cli
script: grunt travis
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.12"
    - node_js: "4"